### create

POST http://localhost:8080/api/v1/favorite/save
Content-Type: application/json

{
  "favorite": {
    "arrival": "유럽",
    "accommodation": "Guest House",
    "startTime": "12-03-2022",
    "endTime": "17-03-2022"
  }
}

###
